source "https://supermarket.getchef.com"

cookbook 'apt'
cookbook 'postfix'
cookbook 'postgresql'
cookbook 'database'
cookbook 'tomcat'
cookbook 'nginx', github: 'miketheman/nginx'
cookbook 'postgis', github: 'realityforge/chef-postgis'
cookbook 'ark', github: 'burtlo/ark'
cookbook 'omnibus_updater'
cookbook 'application_java'
