name             'biodiv'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures biodiv'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'grails-cookbook'
depends          'database'
depends          'postgresql'
depends          'application'
depends          'application_java'
depends          'nginx'
